import csv
import os

# --- Configuration ---
A_FILE_NAME = 'A.csv'
C_FILE_NAME = 'C.csv'
OUTPUT_SPICE_FILE = 'fabric_params.sp'

OSCILLATOR_ROWS = 4
OSCILLATOR_COLS = 4
TOTAL_OSCILLATORS = OSCILLATOR_ROWS * OSCILLATOR_COLS
TOTAL_COUPLERS_PER_OSC = 6

def check_and_create_files():
    """
    Checks if A.csv and C.csv exist. If not, creates them 
    with default '0' values.
    """
    # Check for A.csv (4x4)
    if not os.path.exists(A_FILE_NAME):
        print(f"File '{A_FILE_NAME}' not found. Creating default 4x4 file...")
        default_a_data = [[0] * OSCILLATOR_COLS for _ in range(OSCILLATOR_ROWS)]
        try:
            with open(A_FILE_NAME, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerows(default_a_data)
            print(f"Successfully created '{A_FILE_NAME}'.")
        except IOError as e:
            print(f"Error creating file {A_FILE_NAME}: {e}")
            
    # Check for C.csv (16x6)
    if not os.path.exists(C_FILE_NAME):
        print(f"File '{C_FILE_NAME}' not found. Creating default 16x6 file...")
        default_c_data = [[0] * TOTAL_COUPLERS_PER_OSC for _ in range(TOTAL_OSCILLATORS)]
        try:
            with open(C_FILE_NAME, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerows(default_c_data)
            print(f"Successfully created '{C_FILE_NAME}'.")
        except IOError as e:
            print(f"Error creating file {C_FILE_NAME}: {e}")

def generate_ngspice_params():
    """
    Reads A.csv and C.csv and generates the NGspice .param file.
    """
    print("Reading input files...")
    
    # --- Read A.csv (ROSC enables) ---
    # We will flatten the 4x4 matrix into a 16-element list
    rosc_enables = []
    try:
        with open(A_FILE_NAME, 'r') as f:
            reader = csv.reader(f)
            for row in reader:
                # Ensure we only read 4x4
                if len(rosc_enables) < TOTAL_OSCILLATORS:
                    rosc_enables.extend([int(val) for val in row[:OSCILLATOR_COLS]])
        
        if len(rosc_enables) != TOTAL_OSCILLATORS:
            print(f"Warning: '{A_FILE_NAME}' is not 4x4. Read {len(rosc_enables)} values.")
            # Pad with zeros if file is too small
            rosc_enables.extend([0] * (TOTAL_OSCILLATORS - len(rosc_enables)))
            
    except IOError as e:
        print(f"Error reading {A_FILE_NAME}: {e}")
        return
    except ValueError:
        print(f"Error: '{A_FILE_NAME}' contains non-integer values. Aborting.")
        return

    # --- Read C.csv (Coupler enables) ---
    coupler_enables = []
    try:
        with open(C_FILE_NAME, 'r') as f:
            reader = csv.reader(f)
            for i, row in enumerate(reader):
                if i >= TOTAL_OSCILLATORS:
                    break # Stop reading after 16 rows
                # Ensure we read exactly 6 columns
                row_data = [int(val) for val in row[:TOTAL_COUPLERS_PER_OSC]]
                row_data.extend([0] * (TOTAL_COUPLERS_PER_OSC - len(row_data)))
                coupler_enables.append(row_data)
        
        if len(coupler_enables) != TOTAL_OSCILLATORS:
            print(f"Warning: '{C_FILE_NAME}' does not have 16 rows. Read {len(coupler_enables)}.")
            # Pad with zero-rows if file is too small
            for _ in range(TOTAL_OSCILLATORS - len(coupler_enables)):
                coupler_enables.append([0] * TOTAL_COUPLERS_PER_OSC)
                
    except IOError as e:
        print(f"Error reading {C_FILE_NAME}: {e}")
        return
    except ValueError:
        print(f"Error: '{C_FILE_NAME}' contains non-integer values. Aborting.")
        return

    # --- Write the output .sp file ---
    print(f"Generating '{OUTPUT_SPICE_FILE}'...")
    try:
        with open(OUTPUT_SPICE_FILE, 'w') as f:
            f.write("* === Generated Parameters for 16-ROSC Fabric ===\n")
            f.write("* This file is auto-generated by a Python script.\n")
            f.write("* Do not edit manually.\n\n")
            
            # --- Global Enables ---
            # We set these to 1 (ON) by default.
            # Your NGspice subcircuits will `AND` these with the local enables.
            f.write("* --- Global Enables ---\n")
            f.write(".param ROSC_GEN = 1  * Global enable for all ROSCs\n")
            f.write(".param C_GEN = 1     * Global enable for all Couplers\n\n")
            
            # --- ROSC Local Enables (L_REN) ---
            f.write("* --- ROSC Local Enables (from A.csv) ---\n")
            # We map the flattened 4x4 matrix to ROSC_LEN_1 ... ROSC_LEN_16
            for i in range(TOTAL_OSCILLATORS):
                osc_id = i + 1
                value = rosc_enables[i]
                f.write(f".param ROSC_LEN_{osc_id} = {value}\n")
            
            # --- Coupler Local Enables (L_CEN) ---
            f.write("\n* --- Coupler Local Enables (from C.csv) ---\n")
            # We map the 16x6 matrix to C_LEN_<i>_<j>
            # i = oscillator ID (1-16)
            # j = edge ID (1-6)
            for i in range(TOTAL_OSCILLATORS):
                osc_id = i + 1
                for j in range(TOTAL_COUPLERS_PER_OSC):
                    edge_id = j + 1
                    value = coupler_enables[i][j]
                    f.write(f".param C_LEN_{osc_id}_{edge_id} = {value}\n")
                    
        print(f"Successfully created '{OUTPUT_SPICE_FILE}'.")
        
    except IOError as e:
        print(f"Error writing to {OUTPUT_SPICE_FILE}: {e}")

# --- Main execution ---
if __name__ == "__main__":
    check_and_create_files()
    generate_ngspice_params()